#############################################################################
# Makefile for building: MyBookshelves
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  MyBookshelves.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -o Makefile MyBookshelves.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_XML_LIB -DQT_CORE_LIB
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -m64 -pipe -std=c++11 -O2 -Wall -W -Wno-reorder -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtXml -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = MyBookshelves1.0.0
DISTDIR = /server0/0/2014/cpirlog/Desktop/MyBookshelves-master/.tmp/MyBookshelves1.0.0
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS) -L/usr/X11R6/lib64 -lQt5Widgets -lQt5Gui -lQt5Xml -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		book.cpp \
		bookshelf.cpp \
		database.cpp \
		user.cpp \
		user_normal.cpp \
		user_pro.cpp \
		View/addbookform.cpp \
		View/book_view.cpp \
		administrator.cpp \
		Controller/client.cpp \
		View/administratormainwindow.cpp \
		View/login.cpp \
		View/adduserform.cpp \
		Controller/admin_controller.cpp \
		View/admin_userinfo.cpp \
		View/admin_books.cpp \
		View/admin_bookview.cpp \
		Controller/user_controller.cpp \
		View/user_view.cpp \
		View/bookshelflist_view.cpp \
		View/newbookshelfview.cpp \
		View/reviewslistview.cpp \
		View/accountinfoview.cpp \
		View/finishbookview.cpp \
		moderator.cpp \
		View/reviewview.cpp \
		View/addbookformuser.cpp qrc_resources.cpp \
		moc_addbookform.cpp \
		moc_book_view.cpp \
		moc_administratormainwindow.cpp \
		moc_login.cpp \
		moc_adduserform.cpp \
		moc_admin_userinfo.cpp \
		moc_admin_books.cpp \
		moc_admin_bookview.cpp \
		moc_user_view.cpp \
		moc_bookshelflist_view.cpp \
		moc_newbookshelfview.cpp \
		moc_reviewslistview.cpp \
		moc_accountinfoview.cpp \
		moc_finishbookview.cpp \
		moc_reviewview.cpp \
		moc_addbookformuser.cpp
OBJECTS       = main.o \
		book.o \
		bookshelf.o \
		database.o \
		user.o \
		user_normal.o \
		user_pro.o \
		addbookform.o \
		book_view.o \
		administrator.o \
		client.o \
		administratormainwindow.o \
		login.o \
		adduserform.o \
		admin_controller.o \
		admin_userinfo.o \
		admin_books.o \
		admin_bookview.o \
		user_controller.o \
		user_view.o \
		bookshelflist_view.o \
		newbookshelfview.o \
		reviewslistview.o \
		accountinfoview.o \
		finishbookview.o \
		moderator.o \
		reviewview.o \
		addbookformuser.o \
		qrc_resources.o \
		moc_addbookform.o \
		moc_book_view.o \
		moc_administratormainwindow.o \
		moc_login.o \
		moc_adduserform.o \
		moc_admin_userinfo.o \
		moc_admin_books.o \
		moc_admin_bookview.o \
		moc_user_view.o \
		moc_bookshelflist_view.o \
		moc_newbookshelfview.o \
		moc_reviewslistview.o \
		moc_accountinfoview.o \
		moc_finishbookview.o \
		moc_reviewview.o \
		moc_addbookformuser.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		MyBookshelves.pro book.h \
		bookshelf.h \
		database.h \
		user.h \
		user_normal.h \
		user_pro.h \
		View/addbookform.h \
		View/book_view.h \
		administrator.h \
		Controller/client.h \
		View/administratormainwindow.h \
		View/login.h \
		View/adduserform.h \
		Controller/admin_controller.h \
		View/admin_userinfo.h \
		View/admin_books.h \
		View/admin_bookview.h \
		Controller/user_controller.h \
		View/user_view.h \
		View/bookshelflist_view.h \
		View/newbookshelfview.h \
		View/reviewslistview.h \
		View/accountinfoview.h \
		View/finishbookview.h \
		moderator.h \
		View/reviewview.h \
		View/addbookformuser.h main.cpp \
		book.cpp \
		bookshelf.cpp \
		database.cpp \
		user.cpp \
		user_normal.cpp \
		user_pro.cpp \
		View/addbookform.cpp \
		View/book_view.cpp \
		administrator.cpp \
		Controller/client.cpp \
		View/administratormainwindow.cpp \
		View/login.cpp \
		View/adduserform.cpp \
		Controller/admin_controller.cpp \
		View/admin_userinfo.cpp \
		View/admin_books.cpp \
		View/admin_bookview.cpp \
		Controller/user_controller.cpp \
		View/user_view.cpp \
		View/bookshelflist_view.cpp \
		View/newbookshelfview.cpp \
		View/reviewslistview.cpp \
		View/accountinfoview.cpp \
		View/finishbookview.cpp \
		moderator.cpp \
		View/reviewview.cpp \
		View/addbookformuser.cpp
QMAKE_TARGET  = MyBookshelves
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = MyBookshelves


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET): ui_addbookform.h ui_book_view.h ui_administratormainwindow.h ui_login.h ui_adduserform.h ui_admin_userinfo.h ui_admin_books.h ui_admin_bookview.h ui_user_view.h ui_bookshelflist_view.h ui_newbookshelfview.h ui_reviewslistview.h ui_accountinfoview.h ui_finishbookview.h ui_reviewview.h ui_addbookformuser.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: MyBookshelves.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		MyBookshelves.pro \
		resources.qrc \
		/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Xml.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) -o Makefile MyBookshelves.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
MyBookshelves.pro:
resources.qrc:
/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Xml.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile MyBookshelves.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents book.h bookshelf.h database.h user.h user_normal.h user_pro.h View/addbookform.h View/book_view.h administrator.h Controller/client.h View/administratormainwindow.h View/login.h View/adduserform.h Controller/admin_controller.h View/admin_userinfo.h View/admin_books.h View/admin_bookview.h Controller/user_controller.h View/user_view.h View/bookshelflist_view.h View/newbookshelfview.h View/reviewslistview.h View/accountinfoview.h View/finishbookview.h moderator.h View/reviewview.h View/addbookformuser.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp book.cpp bookshelf.cpp database.cpp user.cpp user_normal.cpp user_pro.cpp View/addbookform.cpp View/book_view.cpp administrator.cpp Controller/client.cpp View/administratormainwindow.cpp View/login.cpp View/adduserform.cpp Controller/admin_controller.cpp View/admin_userinfo.cpp View/admin_books.cpp View/admin_bookview.cpp Controller/user_controller.cpp View/user_view.cpp View/bookshelflist_view.cpp View/newbookshelfview.cpp View/reviewslistview.cpp View/accountinfoview.cpp View/finishbookview.cpp moderator.cpp View/reviewview.cpp View/addbookformuser.cpp $(DISTDIR)/
	$(COPY_FILE) --parents View/addbookform.ui View/book_view.ui View/administratormainwindow.ui View/login.ui View/adduserform.ui View/admin_userinfo.ui View/admin_books.ui View/admin_bookview.ui View/user_view.ui View/bookshelflist_view.ui View/newbookshelfview.ui View/reviewslistview.ui View/accountinfoview.ui View/finishbookview.ui View/reviewview.ui View/addbookformuser.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: resources.qrc \
		resources/img/logo.png
	/usr/lib/x86_64-linux-gnu/qt5/bin/rcc -name resources resources.qrc -o qrc_resources.cpp

compiler_moc_header_make_all: moc_addbookform.cpp moc_book_view.cpp moc_administratormainwindow.cpp moc_login.cpp moc_adduserform.cpp moc_admin_userinfo.cpp moc_admin_books.cpp moc_admin_bookview.cpp moc_user_view.cpp moc_bookshelflist_view.cpp moc_newbookshelfview.cpp moc_reviewslistview.cpp moc_accountinfoview.cpp moc_finishbookview.cpp moc_reviewview.cpp moc_addbookformuser.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_addbookform.cpp moc_book_view.cpp moc_administratormainwindow.cpp moc_login.cpp moc_adduserform.cpp moc_admin_userinfo.cpp moc_admin_books.cpp moc_admin_bookview.cpp moc_user_view.cpp moc_bookshelflist_view.cpp moc_newbookshelfview.cpp moc_reviewslistview.cpp moc_accountinfoview.cpp moc_finishbookview.cpp moc_reviewview.cpp moc_addbookformuser.cpp
moc_addbookform.cpp: book.h \
		Controller/admin_controller.h \
		View/admin_userinfo.h \
		View/admin_books.h \
		View/admin_bookview.h \
		View/addbookform.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/server0/0/2014/cpirlog/Desktop/MyBookshelves-master -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include View/addbookform.h -o moc_addbookform.cpp

moc_book_view.cpp: Controller/user_controller.h \
		database.h \
		moderator.h \
		user_pro.h \
		user_normal.h \
		user.h \
		book.h \
		bookshelf.h \
		View/user_view.h \
		View/book_view.h \
		View/book_view.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/server0/0/2014/cpirlog/Desktop/MyBookshelves-master -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include View/book_view.h -o moc_book_view.cpp

moc_administratormainwindow.cpp: database.h \
		moderator.h \
		user_pro.h \
		user_normal.h \
		user.h \
		book.h \
		bookshelf.h \
		View/addbookform.h \
		Controller/admin_controller.h \
		View/admin_userinfo.h \
		View/admin_books.h \
		View/admin_bookview.h \
		View/adduserform.h \
		administrator.h \
		View/login.h \
		View/administratormainwindow.h \
		Controller/client.h \
		Controller/user_controller.h \
		View/user_view.h \
		View/book_view.h \
		View/administratormainwindow.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/server0/0/2014/cpirlog/Desktop/MyBookshelves-master -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include View/administratormainwindow.h -o moc_administratormainwindow.cpp

moc_login.cpp: View/administratormainwindow.h \
		database.h \
		moderator.h \
		user_pro.h \
		user_normal.h \
		user.h \
		book.h \
		bookshelf.h \
		View/addbookform.h \
		Controller/admin_controller.h \
		View/admin_userinfo.h \
		View/admin_books.h \
		View/admin_bookview.h \
		View/adduserform.h \
		administrator.h \
		View/login.h \
		Controller/client.h \
		Controller/user_controller.h \
		View/user_view.h \
		View/book_view.h \
		View/login.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/server0/0/2014/cpirlog/Desktop/MyBookshelves-master -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include View/login.h -o moc_login.cpp

moc_adduserform.cpp: Controller/admin_controller.h \
		View/admin_userinfo.h \
		View/admin_books.h \
		View/admin_bookview.h \
		View/adduserform.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/server0/0/2014/cpirlog/Desktop/MyBookshelves-master -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include View/adduserform.h -o moc_adduserform.cpp

moc_admin_userinfo.cpp: View/admin_userinfo.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/server0/0/2014/cpirlog/Desktop/MyBookshelves-master -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include View/admin_userinfo.h -o moc_admin_userinfo.cpp

moc_admin_books.cpp: Controller/admin_controller.h \
		View/admin_userinfo.h \
		View/admin_books.h \
		View/admin_bookview.h \
		View/admin_books.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/server0/0/2014/cpirlog/Desktop/MyBookshelves-master -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include View/admin_books.h -o moc_admin_books.cpp

moc_admin_bookview.cpp: Controller/admin_controller.h \
		View/admin_userinfo.h \
		View/admin_books.h \
		View/admin_bookview.h \
		View/admin_bookview.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/server0/0/2014/cpirlog/Desktop/MyBookshelves-master -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include View/admin_bookview.h -o moc_admin_bookview.cpp

moc_user_view.cpp: Controller/user_controller.h \
		database.h \
		moderator.h \
		user_pro.h \
		user_normal.h \
		user.h \
		book.h \
		bookshelf.h \
		View/user_view.h \
		View/book_view.h \
		View/user_view.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/server0/0/2014/cpirlog/Desktop/MyBookshelves-master -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include View/user_view.h -o moc_user_view.cpp

moc_bookshelflist_view.cpp: Controller/user_controller.h \
		database.h \
		moderator.h \
		user_pro.h \
		user_normal.h \
		user.h \
		book.h \
		bookshelf.h \
		View/user_view.h \
		View/book_view.h \
		View/bookshelflist_view.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/server0/0/2014/cpirlog/Desktop/MyBookshelves-master -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include View/bookshelflist_view.h -o moc_bookshelflist_view.cpp

moc_newbookshelfview.cpp: Controller/user_controller.h \
		database.h \
		moderator.h \
		user_pro.h \
		user_normal.h \
		user.h \
		book.h \
		bookshelf.h \
		View/user_view.h \
		View/book_view.h \
		View/newbookshelfview.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/server0/0/2014/cpirlog/Desktop/MyBookshelves-master -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include View/newbookshelfview.h -o moc_newbookshelfview.cpp

moc_reviewslistview.cpp: View/reviewslistview.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/server0/0/2014/cpirlog/Desktop/MyBookshelves-master -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include View/reviewslistview.h -o moc_reviewslistview.cpp

moc_accountinfoview.cpp: View/accountinfoview.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/server0/0/2014/cpirlog/Desktop/MyBookshelves-master -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include View/accountinfoview.h -o moc_accountinfoview.cpp

moc_finishbookview.cpp: View/finishbookview.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/server0/0/2014/cpirlog/Desktop/MyBookshelves-master -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include View/finishbookview.h -o moc_finishbookview.cpp

moc_reviewview.cpp: View/reviewview.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/server0/0/2014/cpirlog/Desktop/MyBookshelves-master -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include View/reviewview.h -o moc_reviewview.cpp

moc_addbookformuser.cpp: Controller/user_controller.h \
		database.h \
		moderator.h \
		user_pro.h \
		user_normal.h \
		user.h \
		book.h \
		bookshelf.h \
		View/user_view.h \
		View/book_view.h \
		View/addbookformuser.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/server0/0/2014/cpirlog/Desktop/MyBookshelves-master -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include View/addbookformuser.h -o moc_addbookformuser.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_addbookform.h ui_book_view.h ui_administratormainwindow.h ui_login.h ui_adduserform.h ui_admin_userinfo.h ui_admin_books.h ui_admin_bookview.h ui_user_view.h ui_bookshelflist_view.h ui_newbookshelfview.h ui_reviewslistview.h ui_accountinfoview.h ui_finishbookview.h ui_reviewview.h ui_addbookformuser.h
compiler_uic_clean:
	-$(DEL_FILE) ui_addbookform.h ui_book_view.h ui_administratormainwindow.h ui_login.h ui_adduserform.h ui_admin_userinfo.h ui_admin_books.h ui_admin_bookview.h ui_user_view.h ui_bookshelflist_view.h ui_newbookshelfview.h ui_reviewslistview.h ui_accountinfoview.h ui_finishbookview.h ui_reviewview.h ui_addbookformuser.h
ui_addbookform.h: View/addbookform.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic View/addbookform.ui -o ui_addbookform.h

ui_book_view.h: View/book_view.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic View/book_view.ui -o ui_book_view.h

ui_administratormainwindow.h: View/administratormainwindow.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic View/administratormainwindow.ui -o ui_administratormainwindow.h

ui_login.h: View/login.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic View/login.ui -o ui_login.h

ui_adduserform.h: View/adduserform.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic View/adduserform.ui -o ui_adduserform.h

ui_admin_userinfo.h: View/admin_userinfo.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic View/admin_userinfo.ui -o ui_admin_userinfo.h

ui_admin_books.h: View/admin_books.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic View/admin_books.ui -o ui_admin_books.h

ui_admin_bookview.h: View/admin_bookview.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic View/admin_bookview.ui -o ui_admin_bookview.h

ui_user_view.h: View/user_view.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic View/user_view.ui -o ui_user_view.h

ui_bookshelflist_view.h: View/bookshelflist_view.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic View/bookshelflist_view.ui -o ui_bookshelflist_view.h

ui_newbookshelfview.h: View/newbookshelfview.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic View/newbookshelfview.ui -o ui_newbookshelfview.h

ui_reviewslistview.h: View/reviewslistview.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic View/reviewslistview.ui -o ui_reviewslistview.h

ui_accountinfoview.h: View/accountinfoview.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic View/accountinfoview.ui -o ui_accountinfoview.h

ui_finishbookview.h: View/finishbookview.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic View/finishbookview.ui -o ui_finishbookview.h

ui_reviewview.h: View/reviewview.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic View/reviewview.ui -o ui_reviewview.h

ui_addbookformuser.h: View/addbookformuser.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic View/addbookformuser.ui -o ui_addbookformuser.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp Controller/client.h \
		database.h \
		moderator.h \
		user_pro.h \
		user_normal.h \
		user.h \
		book.h \
		bookshelf.h \
		View/login.h \
		View/administratormainwindow.h \
		View/addbookform.h \
		Controller/admin_controller.h \
		View/admin_userinfo.h \
		View/admin_books.h \
		View/admin_bookview.h \
		View/adduserform.h \
		administrator.h \
		Controller/user_controller.h \
		View/user_view.h \
		View/book_view.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

book.o: book.cpp book.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o book.o book.cpp

bookshelf.o: bookshelf.cpp bookshelf.h \
		book.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bookshelf.o bookshelf.cpp

database.o: database.cpp database.h \
		moderator.h \
		user_pro.h \
		user_normal.h \
		user.h \
		book.h \
		bookshelf.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o database.o database.cpp

user.o: user.cpp user.h \
		book.h \
		bookshelf.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o user.o user.cpp

user_normal.o: user_normal.cpp user_normal.h \
		user.h \
		book.h \
		bookshelf.h \
		database.h \
		moderator.h \
		user_pro.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o user_normal.o user_normal.cpp

user_pro.o: user_pro.cpp user_pro.h \
		user_normal.h \
		user.h \
		book.h \
		bookshelf.h \
		database.h \
		moderator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o user_pro.o user_pro.cpp

addbookform.o: View/addbookform.cpp View/addbookform.h \
		book.h \
		Controller/admin_controller.h \
		View/admin_userinfo.h \
		View/admin_books.h \
		View/admin_bookview.h \
		ui_addbookform.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o addbookform.o View/addbookform.cpp

book_view.o: View/book_view.cpp View/book_view.h \
		Controller/user_controller.h \
		database.h \
		moderator.h \
		user_pro.h \
		user_normal.h \
		user.h \
		book.h \
		bookshelf.h \
		View/user_view.h \
		ui_book_view.h \
		View/bookshelflist_view.h \
		View/reviewslistview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o book_view.o View/book_view.cpp

administrator.o: administrator.cpp administrator.h \
		database.h \
		moderator.h \
		user_pro.h \
		user_normal.h \
		user.h \
		book.h \
		bookshelf.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o administrator.o administrator.cpp

client.o: Controller/client.cpp Controller/client.h \
		database.h \
		moderator.h \
		user_pro.h \
		user_normal.h \
		user.h \
		book.h \
		bookshelf.h \
		View/login.h \
		View/administratormainwindow.h \
		View/addbookform.h \
		Controller/admin_controller.h \
		View/admin_userinfo.h \
		View/admin_books.h \
		View/admin_bookview.h \
		View/adduserform.h \
		administrator.h \
		Controller/user_controller.h \
		View/user_view.h \
		View/book_view.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o client.o Controller/client.cpp

administratormainwindow.o: View/administratormainwindow.cpp View/administratormainwindow.h \
		database.h \
		moderator.h \
		user_pro.h \
		user_normal.h \
		user.h \
		book.h \
		bookshelf.h \
		View/addbookform.h \
		Controller/admin_controller.h \
		View/admin_userinfo.h \
		View/admin_books.h \
		View/admin_bookview.h \
		View/adduserform.h \
		administrator.h \
		View/login.h \
		Controller/client.h \
		Controller/user_controller.h \
		View/user_view.h \
		View/book_view.h \
		ui_administratormainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o administratormainwindow.o View/administratormainwindow.cpp

login.o: View/login.cpp View/login.h \
		View/administratormainwindow.h \
		database.h \
		moderator.h \
		user_pro.h \
		user_normal.h \
		user.h \
		book.h \
		bookshelf.h \
		View/addbookform.h \
		Controller/admin_controller.h \
		View/admin_userinfo.h \
		View/admin_books.h \
		View/admin_bookview.h \
		View/adduserform.h \
		administrator.h \
		Controller/client.h \
		Controller/user_controller.h \
		View/user_view.h \
		View/book_view.h \
		ui_login.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o login.o View/login.cpp

adduserform.o: View/adduserform.cpp View/adduserform.h \
		Controller/admin_controller.h \
		View/admin_userinfo.h \
		View/admin_books.h \
		View/admin_bookview.h \
		ui_adduserform.h \
		View/administratormainwindow.h \
		database.h \
		moderator.h \
		user_pro.h \
		user_normal.h \
		user.h \
		book.h \
		bookshelf.h \
		View/addbookform.h \
		administrator.h \
		View/login.h \
		Controller/client.h \
		Controller/user_controller.h \
		View/user_view.h \
		View/book_view.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o adduserform.o View/adduserform.cpp

admin_controller.o: Controller/admin_controller.cpp Controller/admin_controller.h \
		View/admin_userinfo.h \
		View/admin_books.h \
		View/admin_bookview.h \
		View/administratormainwindow.h \
		database.h \
		moderator.h \
		user_pro.h \
		user_normal.h \
		user.h \
		book.h \
		bookshelf.h \
		View/addbookform.h \
		View/adduserform.h \
		administrator.h \
		View/login.h \
		Controller/client.h \
		Controller/user_controller.h \
		View/user_view.h \
		View/book_view.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o admin_controller.o Controller/admin_controller.cpp

admin_userinfo.o: View/admin_userinfo.cpp View/admin_userinfo.h \
		ui_admin_userinfo.h \
		View/administratormainwindow.h \
		database.h \
		moderator.h \
		user_pro.h \
		user_normal.h \
		user.h \
		book.h \
		bookshelf.h \
		View/addbookform.h \
		Controller/admin_controller.h \
		View/admin_books.h \
		View/admin_bookview.h \
		View/adduserform.h \
		administrator.h \
		View/login.h \
		Controller/client.h \
		Controller/user_controller.h \
		View/user_view.h \
		View/book_view.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o admin_userinfo.o View/admin_userinfo.cpp

admin_books.o: View/admin_books.cpp View/admin_books.h \
		Controller/admin_controller.h \
		View/admin_userinfo.h \
		View/admin_bookview.h \
		ui_admin_books.h \
		View/addbookform.h \
		book.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o admin_books.o View/admin_books.cpp

admin_bookview.o: View/admin_bookview.cpp View/admin_bookview.h \
		Controller/admin_controller.h \
		View/admin_userinfo.h \
		View/admin_books.h \
		ui_admin_bookview.h \
		book.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o admin_bookview.o View/admin_bookview.cpp

user_controller.o: Controller/user_controller.cpp Controller/user_controller.h \
		database.h \
		moderator.h \
		user_pro.h \
		user_normal.h \
		user.h \
		book.h \
		bookshelf.h \
		View/user_view.h \
		View/book_view.h \
		View/bookshelflist_view.h \
		View/newbookshelfview.h \
		View/accountinfoview.h \
		View/finishbookview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o user_controller.o Controller/user_controller.cpp

user_view.o: View/user_view.cpp View/user_view.h \
		Controller/user_controller.h \
		database.h \
		moderator.h \
		user_pro.h \
		user_normal.h \
		user.h \
		book.h \
		bookshelf.h \
		View/book_view.h \
		ui_user_view.h \
		View/newbookshelfview.h \
		View/accountinfoview.h \
		View/addbookformuser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o user_view.o View/user_view.cpp

bookshelflist_view.o: View/bookshelflist_view.cpp View/bookshelflist_view.h \
		Controller/user_controller.h \
		database.h \
		moderator.h \
		user_pro.h \
		user_normal.h \
		user.h \
		book.h \
		bookshelf.h \
		View/user_view.h \
		View/book_view.h \
		ui_bookshelflist_view.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bookshelflist_view.o View/bookshelflist_view.cpp

newbookshelfview.o: View/newbookshelfview.cpp View/newbookshelfview.h \
		Controller/user_controller.h \
		database.h \
		moderator.h \
		user_pro.h \
		user_normal.h \
		user.h \
		book.h \
		bookshelf.h \
		View/user_view.h \
		View/book_view.h \
		ui_newbookshelfview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o newbookshelfview.o View/newbookshelfview.cpp

reviewslistview.o: View/reviewslistview.cpp View/reviewslistview.h \
		ui_reviewslistview.h \
		View/reviewview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o reviewslistview.o View/reviewslistview.cpp

accountinfoview.o: View/accountinfoview.cpp View/accountinfoview.h \
		ui_accountinfoview.h \
		Controller/user_controller.h \
		database.h \
		moderator.h \
		user_pro.h \
		user_normal.h \
		user.h \
		book.h \
		bookshelf.h \
		View/user_view.h \
		View/book_view.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o accountinfoview.o View/accountinfoview.cpp

finishbookview.o: View/finishbookview.cpp View/finishbookview.h \
		ui_finishbookview.h \
		Controller/user_controller.h \
		database.h \
		moderator.h \
		user_pro.h \
		user_normal.h \
		user.h \
		book.h \
		bookshelf.h \
		View/user_view.h \
		View/book_view.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o finishbookview.o View/finishbookview.cpp

moderator.o: moderator.cpp moderator.h \
		user_pro.h \
		user_normal.h \
		user.h \
		book.h \
		bookshelf.h \
		database.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moderator.o moderator.cpp

reviewview.o: View/reviewview.cpp View/reviewview.h \
		ui_reviewview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o reviewview.o View/reviewview.cpp

addbookformuser.o: View/addbookformuser.cpp View/addbookformuser.h \
		Controller/user_controller.h \
		database.h \
		moderator.h \
		user_pro.h \
		user_normal.h \
		user.h \
		book.h \
		bookshelf.h \
		View/user_view.h \
		View/book_view.h \
		ui_addbookformuser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o addbookformuser.o View/addbookformuser.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

moc_addbookform.o: moc_addbookform.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_addbookform.o moc_addbookform.cpp

moc_book_view.o: moc_book_view.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_book_view.o moc_book_view.cpp

moc_administratormainwindow.o: moc_administratormainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_administratormainwindow.o moc_administratormainwindow.cpp

moc_login.o: moc_login.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_login.o moc_login.cpp

moc_adduserform.o: moc_adduserform.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_adduserform.o moc_adduserform.cpp

moc_admin_userinfo.o: moc_admin_userinfo.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_admin_userinfo.o moc_admin_userinfo.cpp

moc_admin_books.o: moc_admin_books.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_admin_books.o moc_admin_books.cpp

moc_admin_bookview.o: moc_admin_bookview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_admin_bookview.o moc_admin_bookview.cpp

moc_user_view.o: moc_user_view.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_user_view.o moc_user_view.cpp

moc_bookshelflist_view.o: moc_bookshelflist_view.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_bookshelflist_view.o moc_bookshelflist_view.cpp

moc_newbookshelfview.o: moc_newbookshelfview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_newbookshelfview.o moc_newbookshelfview.cpp

moc_reviewslistview.o: moc_reviewslistview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_reviewslistview.o moc_reviewslistview.cpp

moc_accountinfoview.o: moc_accountinfoview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_accountinfoview.o moc_accountinfoview.cpp

moc_finishbookview.o: moc_finishbookview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_finishbookview.o moc_finishbookview.cpp

moc_reviewview.o: moc_reviewview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_reviewview.o moc_reviewview.cpp

moc_addbookformuser.o: moc_addbookformuser.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_addbookformuser.o moc_addbookformuser.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

